FROM %BASE_IMG%

LABEL org.opencontainers.image.source https://github.com/eflows4hpc/image_creation

COPY %APPDIR% /%APPDIR%
COPY software_catalog /software_catalog
COPY .spack /root/.spack

RUN  spack find && spack -e /%APPDIR% install && spack gc -y

RUN  echo ". /opt/spack/share/spack/setup-env.sh && cd /%APPDIR% && spack env activate ." >> /etc/profile.d/z10_spack_environment.sh

