FROM %BASE_IMG%

LABEL org.opencontainers.image.source https://github.com/eflows4hpc/image_creation

COPY %APPDIR% /%APPDIR%
COPY software-catalog /software-catalog
COPY .spack /.spack

RUN  spack -C /.spack find && cat /%APPDIR%/spack.yaml && spack -C /.spack -e /%APPDIR% install -v -j2 && spack gc -y

RUN  echo ". /opt/spack/share/spack/setup-env.sh && cd /%APPDIR% && spack -C /.spack env activate ." >> /etc/profile.d/z10_spack_environment.sh

